version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=SpringTestCatalogDb
      - MYSQL_USER=spring-test-catalog-user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
  web-app:
    image: spring-test-catalog
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=spring-test-catalog-mysql
      - DATABASE_USER=spring-test-catalog-user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=SpringTestCatalogDb
      - DATABASE_PORT=3306
